version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    labels:
      - "logging=true"
    ports:
      - "8891:8890"
    logging: *default-logging
  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.0.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  search:
    build: .
    ports:
      - 8888:80
    environment:
      RACK_ENV: "development"
      NUMBER_OF_THREADS: 4 # overwrite for development
      JRUBY_OPTIONS: "-J-Xmx8g" # overwrite for development
    # links:
    # - db:database
    volumes:
      - /media/wout/Data/Workspace/Redpencil/mu-search/:/app/
      - ./config/config.json:/config/config.json
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
